import tkinter as tk
def add_pet():
    pet_name = name_entry.get()
    pet_age = age_entry.get()
    result_label.config(text=f"Added {pet_name}, Age: {pet_age}.")
window = tk.Tk()
window.title("Pet Adoption Management System")
name_label = tk.Label(window, text="Pet Name:")
name_label.grid(row=0, column=0)
name_entry = tk.Entry(window)
name_entry.grid(row=0, column=1)
age_label =tk.Label(window, text="Pet Age:")
age_label.grid(row=1, column=0)
age_entry = tk.Entry(window)
age_entry.grid(row=1, column=1)
add_pet_button = tk.Button(window, text="Add Pet", command=add_pet)
add_pet_button.grid(row=2, column=1)
result_label= tk.Label(window, text=)
result_label.grid(row3, columnspan=2)
window.mainloop()
